### PR TITLE
fix: use moby/term rather than our own term package

### PR DESCRIPTION
**Pull request by bakins**
## Related issue
https://github.com/ory/dockertest/issues/212
https://github.com/ory/dockertest/issues/208

## Proposed changes

Use https://github.com/moby/term rather than the term package introduced in https://github.com/ory/dockertest/pull/122

There is only a single call to term in the code base at https://github.com/ory/dockertest/blob/5c873159c1b19fd8ff2c60f7077a0aebf9fd36b2/docker/pkg/jsonmessage/jsonmessage.go#L129

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation within the code base (if appropriate)

## Further comments

I considered editing docker/pkg/term to include the fixes from https://github.com/moby/term/pull/16 but dockertest only has a single call to the term package.

### CODE REVIEW

**Comment by aeneasr** [comment]
So originally I added docker as a direct dependency because there was no other way of consuming the Docker API without writing a lot of curl myself. The problem was however, that Docker pulled quite a lot of code that wasn't actually used. I could not find a way (at the time) to prevent those unused modules from being pulled. I still think it's not possible.

However, maybe today there is a much better option to talk to Docker's API? In which case we would probably also circumvent all the build issues and stuff! Maybe you know this?

**Comment by bakins** [comment]
@aeneasr I haven't looked at the full dockerclient in a while.  I was mostly interested in fixing the issue with having to pin `sys` across a large number of projects where I use dockertest.

I don't mind looking into docker client, but I just wanted to offer up a PR to fix the current pressing issue quickly :)  This PR only pulls in moby/term, which does not pull in any additional dependencies beyond what dockertest already depends on: https://github.com/ory/dockertest/pull/227/files#diff-37aff102a57d3d7b797f152915a6dc16

**Comment by bakins** [comment]
It seems the  "official" [dockerclient](https://github.com/moby/moby/tree/master/client) still pulls in a large number of dependencies.  The moby/term package in this PR does not pull in any additional dependencies.

I'd like to not have to pin github.com/x/sys/ to a specific version anymore.  If the approach in this PR is not acceptable, what alternative would be? I'm happy to do a PR.

Thanks!

**Comment by aeneasr** [comment]
Ok, sounds good and sorry for the late review, it was a busy week :)

**Pull request merged**
