### PR TITLE
BuildOptions for BuildAndRun

### PR DESCRIPTION
**Pull request by DarthRamone**
## Proposed changes

User should be able to specify context path, because of Dockerfile can be in sub-directory and in that case, context path will be Dockerfile path, which is wrong and BuildAndRun method become useless. 

I propose new BuildOptions struct, with Dockerfile and ContextDir fields, that can be passed along with RunOptions to BuildAndRunWithOptions method. BuildAndRunWithOptions become more flexible.  

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.md)
- [x] I have read the [security policy](SECURITY.md)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)

### CODE REVIEW

**Review by aeneasr — CHANGES_REQUESTED** [review]
Because this is a BC break it would make more sense to add another option instead of changing the existing one. However, the changes look good!

**Comment by DarthRamone** [comment]
Now looks done, but coverage decreased :) 
As far as I understand, all Build* methods are not covered

UPD: nah, not all

**Comment by aeneasr** [comment]
> Now looks done, but coverage decreased :)

You could add a small test for this and code coverage would increase :)

**Comment by DarthRamone** [comment]
My latest commit fixes it. New method uses old covered method, so it is covered too. All checks have passed, these changes doesn't affect coverage

**Comment by DarthRamone** [comment]
@aeneasr hi. In case of you missed my last comment, https://github.com/ory/dockertest/pull/167/commits/920967b145c0adee742d5c22c73c0339448bd64f this commit fixes decreased coverage, and my changes are covered with already existed tests.

**Comment by aeneasr** [comment]
Oh yeah, thank you and sorry :)

**Pull request merged**
