### PR TITLE
Changed example so call to Purge() is deferred

### PR DESCRIPTION
**Pull request by jpeletier**

### CODE REVIEW

**Review by aeneasr — COMMENTED** [review]
Thank you, this looks great! Could you please sign the CLA (just two clicks), then we can merge it right away!

**Comment by aeneasr** [comment]
Sorry, accidental close

**Comment by aeneasr** [comment]
Closing due to inactivity

**Comment by jpeletier** [comment]
You should at least grab this change because I think it is good for your documentation. I just don't see myself signing agreements for contributions to every open source project I interact with. Everybody understands a contribution is voluntary. Cheers!

**Comment by aeneasr** [comment]
Sorry, I can't merge PRs without agreements signed even if I think that your changes are valuable! If you ever reconsider I'll merge it right away :)

**Pull request closed without merging**
