### PR TITLE
feat: fall back to podman if available

### PR DESCRIPTION
**Pull request by SoMuchForSubtlety**
## Related Issue or Design Document

This PR changes the default host on Unix to podman if docker is not available, but podman is. This makes tests work on more systems by default without the need to set an environment variable.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by SoMuchForSubtlety** [comment]
Any chance of getting a review?

**Comment by samox73** [comment]
We also need this, is there any progress?

**Comment by adzimzf** [comment]
up, I also need this

**Review by alnr — APPROVED** [review]
Thank you!

**Pull request merged**
