### PR TITLE
Remove Travis-CI Setting up description from README.md

### LINKED ISSUE #154: Remove Travis-CI set-up description
**Is your feature request related to a problem? Please describe.**
According to the following posts, Travis-CI had  two Linux infrastructures which are containers and virtual machines, but recently Travis-CI was combined two Linux infrastructures into a virtual machine-based Linux infrastructures.

https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

So, we do not need add the following settings at travis.yml.

```yml
# Sudo is required for docker
sudo: required

# Enable docker
services:
  - docker
```

Actually I removed above settings from my travis.yml, but my tests passed Travis-CI checks.

**Describe the solution you'd like**
I'd like to remove the section of `Setting up Travis-CI` from [README.md](https://github.com/ory/dockertest/blob/v3/README.md)

### PR DESCRIPTION
**Pull request by sekky0905**
Remove Setting up Travis-CI

## Related issue
Resolves #154  as discussed with @aeneasr .

## Proposed changes
Remove the section of Setting up Travis-CI from README.md.

## Checklist
- [x] I have read the [contributing guidelines](CONTRIBUTING.md)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [hi@ory.sh](mailto:hi@ory.sh)) from the maintainers to push the changes.
- [x] I signed the [Developer's Certificate of Origin](https://github.com/ory/keto/blob/master/CONTRIBUTING.md#developers-certificate-of-origin)
by signing my commit(s). You can amend your signature to the most recent commit by using `git commit --amend -s`. If you
amend the commit, you might need to force push using `git push --force HEAD:<branch>`. Please be very careful when using
force push.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation within the code base (if appropriate)

## Further comments
NaN

### CODE REVIEW

**Comment by aeneasr** [comment]
Please update the table of contents as well :)

**Comment by sekky0905** [comment]
> Please update the table of contents as well :)

sorry, I fixed.
Am I ok?

**Comment by aeneasr** [comment]
Not yet :) What I mean is this line: https://github.com/ory/dockertest/pull/155/files#diff-04c6e90faac2675aa89e2176d2eec7d8R16

**Comment by sekky0905** [comment]
> Not yet :) What I mean is this line: https://github.com/ory/dockertest/pull/155/files#diff-04c6e90faac2675aa89e2176d2eec7d8R16

I'm very sorry, I misunderstood.
I fixed it.
Thank you for your telling.

**Comment by aeneasr** [comment]
Don't worry about it! Thank you for your contribution!

**Pull request merged**
