### PR TITLE
fix: allow windows mounts to reference docker volumes

### PR DESCRIPTION
**Pull request by RichieSams**
MountParser assumes that it's parsing a local absolute path for the `src` arg. However, it's also legal to use a named docker volume. This change allows for that case.

- [ x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ x ] I have read the [security policy](../security/policy).
- [ x ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ x ] I have added tests that prove my fix is effective or that my feature
      works.
- [ x ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
Does that keep backwards compatibility? If so, could you reference this in some docs from docker? Thank you! :)

**Comment by RichieSams** [comment]
https://docs.docker.com/storage/bind-mounts/#choose-the--v-or---mount-flag
https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag

From what I can tell from those docs, even what is put for non windows is incorrect.
The format is:
```
<src>:<dest>[:<options>]
```

`options` is optional.
For volume mounting, `src` is the name of a volume
For bind-mounts, `src` is the absolute path on the host

For bind-mounts on Windows, since `src` is required to be an absolute path, `src` will have an extra colon, due to the "drive".

I will update the PR accordingly

**Comment by RichieSams** [comment]
I found it difficult to try to re-capture all of the edge cases. So instead, I'm importing / using the same function used by docker-cli to parse the volume string.

**Comment by aeneasr** [comment]
That makes a ton of sense, thank you!

**Pull request merged**
